### ISSUE TITLE
libdwarf backend 

### ISSUE THREAD

**Issue by mariuszmaximus** [Febbe/stacktrace#13]
Is possible add libdwarf support ? 
I tested on msys2  (gcc,clang) and all works correct 
https://developer.ibm.com/articles/au-dwarf-debug-format/

**Comment by Febbe** [comment]
This should be possible theoretically. But I have some problems with it:
 - I have very little time, it is enough to maintain this repo, but I can't afford to write a new backend right now.
 - llibbacktrace, which is already an implemented backend, supports more than dwarf, but I haven't managed to get it working for msys2+X (yet)
   - Probably, only a lib or compile flag is missing
 - I try to implement the stacktraces as similar as the future implementations of the 3 main STLs (libstdc++, libc++, msvcstl). Libdwarf is used by none of them. 

But I am willing to maintain it, if you or someone else makes a pull request.
I honestly think, that it would be better, if you try to fix libbacktrace. Boost::stacktrace also uses it and it should work there. So it is most likely a bug in my configuration code.

**Comment by mariuszmaximus** [comment]
Thank you for your answer
I'm waiting for libbacktrace on msys2
I'm closing the thread

**Comment by Febbe** [comment]
@mariuszmaximus when linking with the `-no-pie` option (cmake: `target_link_options(stacktrace INTERFACE -no-pie)`), libbacktrace works. This is due to the fact that libbacktrace [does not implement ASLR yet](https://github.com/ianlancetaylor/libbacktrace/issues/103). I currently don't know how to implement that for PE+COFF in libbacktrace, so one have to live with the possible security risk.
